version: '3'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: msql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=haste
      - MYSQL_USER=hastes
      - MYSQL_PASSWORD=2020
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"
    # names
volumes:
  my-db:
