version: '3'
services:
  app:
    container_name: docker-haste-docker
    restart: always
    build: .
    ports:
      - '80:3002'
    command: npm run dev
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
